services:
  notificator:
    image: ghcr.io/e-gulakhmet/obsidian-tasks-notificator:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TASKS_DIR_HOST}:${TASKS_DIR}:ro
      - notificator_data:/data

volumes:
  notificator_data:
