services:
  notificator:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-local}/obsidian-tasks-notificator:latest
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TASKS_DIR_HOST}:/vault/tasks:ro
